name: my_python_plugin
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/malikumair24800/my_python_plugin

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MyPythonPlugin
